# This is the config file of the demo instance that is deployed on https://nellygateway.azurewebsites.net
hostUri: env:HOSTURI

routes:
  frontend:
    type: static
    path: /**
    url: https://nellyconduitfrontend.z1.web.core.windows.net
    allowAnonymous: yes
  api:
    type: apiforspa
    path: /api/**
    url: https://nelly-conduit-backend.azurewebsites.net
    allowAnonymous: yes
  echo:
    type: apiforspa
    path: /echo/**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: yes
  authenticated:
    type: apiforspa
    path: /secure/**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: no

loginProviders:
  google:
    type: oidc
    with:
      authEndpoint: https://accounts.google.com/o/oauth2/auth
      tokenEndpoint: https://oauth2.googleapis.com/token
      clientId: 372143946338-48et57uhmcumku7am3ocvva0idc7u0td.apps.googleusercontent.com
      clientSecret: env:GOOGLE_CLIENT_SECRET
      scopes: [ "openid", "email", "profile"]

  github:
    type: github
    with:
      authEndpoint: https://github.com/login/oauth/authorize
      tokenEndpoint: https://github.com/login/oauth/access_token
      clientId: env:GITHUB_CLIENT_ID
      clientSecret: env:GITHUB_CLIENT_SECRET
      scopes: [ "user", "email" ]

  auth0:
    type: oidc
    with:
      authEndpoint: https://dev-b6-eperz.eu.auth0.com/authorize
      tokenEndpoint: https://dev-b6-eperz.eu.auth0.com/oauth/token
      clientId: ShvOJHRoa1dH35Oqq17GNcchZDbEmgcz
      clientSecret: env:AUTH0_CLIENT_SECRET
      scopes: [ "openid", "email" ]

securityProfiles:
  apiforspa:
    csrfProtection: samesite-strict-cookie
    userMapping:
      type: "jwt-mapping"
      settings:
        headerName: "Authorization"
        headerPrefix: "Bearer "
        audience: "<<route-url>>"
        issuer: "<<hostUri>>"
        tokenLifetimeSeconds: 30
        signatureImplementation: "rsa"
        signatureSettings: {}
        mappings:
          sub:            <session.provider>:<session.userId>
          picture:        <mappings.picture>
          email:          <mappings.email>
          proxy:          "OWASP Application Gateway"
          sessionId:      <session.id>

traceProfile:
  forwardIncomingTrace: false
  maxLengthIncomingTrace: 254
  acceptAdditionalTraceInfo: false
  maxLengthAdditionalTraceInfo: 254
  sendTraceResponse: true
  type: w3cTrace