# This is the config file of the demo instance that is deployed on https://nellygateway.azurewebsites.net
hostUri: env:HOSTURI
nellyApiKey: env:NELLY_API_KEY

routes:
  frontend:
    type: static
    path: /**
    url: https://nellyconduitfrontend.z1.web.core.windows.net
    allowAnonymous: yes
  api:
    type: apiforspa
    path: /api/**
    url: https://nelly-conduit-backend.azurewebsites.net
    allowAnonymous: yes
  echo:
    type: webapplication
    path: /echo/**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: yes
  authenticated:
    type: webapplication
    path: /secure/**
    url: https://nellydemoapp.azurewebsites.net
    allowAnonymous: no

loginProviders:
  google:
    type: oidc
    with:
      authEndpoint: https://accounts.google.com/o/oauth2/auth
      tokenEndpoint: https://oauth2.googleapis.com/token
      clientId: 372143946338-48et57uhmcumku7am3ocvva0idc7u0td.apps.googleusercontent.com
      clientSecret: env:GOOGLE_CLIENT_SECRET
      scopes: [ "openid", "email", "profile"]

  github:
    type: github
    with:
      authEndpoint: https://github.com/login/oauth/authorize
      tokenEndpoint: https://github.com/login/oauth/access_token
      clientId: 163ad3b08c3829216ba1
      clientSecret: env:GITHUB_CLIENT_SECRET
      scopes: [ "user", "email" ]

  auth0:
    type: oidc
    with:
      authEndpoint: https://dev-b6-eperz.eu.auth0.com/authorize
      tokenEndpoint: https://dev-b6-eperz.eu.auth0.com/oauth/token
      clientId: ShvOJHRoa1dH35Oqq17GNcchZDbEmgcz
      clientSecret: env:AUTH0_CLIENT_SECRET
      scopes: [ "openid", "email" ]

securityProfiles:
  static:
    allowedMethods: [ "GET", "HEAD", "OPTIONS" ]
    csrfProtection: none
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-XSS-Protection: 1; mode=block;
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      Content-Security-Policy: upgrade-insecure-requests;base-uri 'self';object-src 'self'
      Permissions-Policy: geolocation=(),notifications=(),push=(),microphone=(),camera=(),speaker=(),vibrate=(),fullscreen=(),payment=(),usb=(),magnetometer=(),gyroscope=(),accelerometer=()
      Strict-Transport-Security: max-age=31536000; includeSubDomains

  webapplication:
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-XSS-Protection: 1;mode=block;
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      Content-Security-Policy: upgrade-insecure-requests;base-uri 'self';object-src 'self'
      Permissions-Policy: geolocation=(),notifications=(),push=(),microphone=(),camera=(),speaker=(),vibrate=(),fullscreen=(),payment=(),usb=(),magnetometer=(),gyroscope=(),accelerometer=()
      Strict-Transport-Security: max-age=31536000; includeSubDomains

  apiforspa:
    allowedMethods: [ "GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS", "HEAD" ]
    csrfProtection: none
    responseHeaders:
      Server: <<remove>>
      X-Powered-By: <<remove>>
      X-Content-Type-Options: nosniff
      Referrer-Policy: no-referrer
      Content-Security-Policy: upgrade-insecure-requests; default-src 'none'; base-uri 'self'; frame-ancestors 'none'
      Strict-Transport-Security: max-age=31536000; includeSubDomains

  raw-proxy:
    responseHeaders:
